spring.application.name=springSecurity

#if we don't use the UserDetailsService()
#in the last version these do nothing because we store users in db
spring.security.user.name=test
spring.security.user.password=1234

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#default = lax, strict -> no cross site access even with csrf token
server.servlet.session.cookie.same-site=strict
